#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/p/project/cjzam11/kitayama1/opt/nrn-master"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/p/project/cjzam11/kitayama1/opt/nrn-master/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/p/project/cjzam11/kitayama1/b04feb12/x86_64/.libs/libnrnmech.so" "$@"
