#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/usr4/c74014i/opt/nrn-master"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/usr4/c74014i/opt/nrn-master/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/usr4/c74014i/b04feb12/x86_64/.libs/libnrnmech.so" "$@"
